version: '3'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile.django.dev
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE={{ project_name }}.settings
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - ./:/app
    ports: 
      - 8000:8000
      - 8888:8888
    depends_on:
      - static_app

  static_app:
    build:
      context: .
      dockerfile: Dockerfile.node.dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    ports: 
      - 8080:8080
